version: "3.9"

services:

  # Bot API service
  bot-api:
    environment:
      TELEGRAM_WEB_APP_URL: https://${NGROK_DOMAIN}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    restart: on-failure
    build:
      context: ./api
    ports:
      - 3000:3001

  # Bot UI in development mode
  bot-ui:
    restart: on-failure
    volumes:
      - ./ui/src:/app/src
      - ./ui/public:/app/public
      - ./ui/index.html:/app/index.html
      - ./ui/vite.config.js:/app/vite.config.js
    build:
      context: ./ui
      dockerfile: dev.dockerfile

  # Nginx proxy to forward request to UI and API
  dev-proxy:
    image: nginx:stable-alpine
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      API_URL: http://bot-api:3000
      UI_URL: http://bot-ui:3000
    restart: on-failure
    volumes:
      - ./proxy.template:/etc/nginx/templates/default.conf.template

  # Ngrok service
  ngrok:
    image: wernight/ngrok 
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    restart: on-failure
    networks:
      - webnet
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    command: ["ngrok", "http", "--domain=hornet-driving-loosely.ngrok-free.app", "3000"]

networks:
  webnet: